from .albums import get_fully_populated_album, get_minimally_populated_album
from .artists import get_fully_populated_artist, get_minimally_populated_artist
from .tracks import get_fully_populated_track, get_minimally_populated_track