# Generated by Django 5.1.7 on 2025-03-13 18:36

import django.core.validators
import django.db.models.deletion
import master_collection.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('bio', models.TextField(blank=True)),
                ('origin', models.CharField(blank=True, verbose_name='origin city')),
                ('profile', models.ImageField(blank=True, upload_to=master_collection.models.Artist.art_dir)),
                ('banner', models.ImageField(blank=True, upload_to=master_collection.models.Artist.art_dir)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.TextField(blank=True)),
                ('release_date', models.DateField()),
                ('album_cover', models.ImageField(blank=True, upload_to=master_collection.models.Album.art_dir, validators=[django.core.validators.validate_image_file_extension])),
                ('spine_art', models.ImageField(blank=True, upload_to=master_collection.models.Album.art_dir, validators=[django.core.validators.validate_image_file_extension])),
                ('contributing_artists', models.ManyToManyField(blank=True, related_name='contributing_albums', to='master_collection.artist')),
                ('release_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='master_collection.artist')),
            ],
            options={
                'ordering': ['release_artist', '-release_date'],
                'unique_together': {('release_artist', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('order', models.IntegerField()),
                ('lyrics', models.TextField(blank=True)),
                ('master_recording', models.FileField(upload_to=master_collection.models.Track.master_upload_dir, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['flac'])])),
                ('streamable_recording', models.FileField(blank=True, upload_to=master_collection.models.Track.streamable_upload_dir, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['aac'])])),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_collection.album')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('album', 'order')},
            },
        ),
    ]
