# Generated by Django 5.1.7 on 2025-03-12 00:17

import django.core.validators
import django.db.models.deletion
import master_collection.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('master_collection', '0001_initial'), ('master_collection', '0002_artist_banner_artist_members_artist_origin_and_more'), ('master_collection', '0003_remove_recording_album_remove_recording_lyrics_and_more')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(unique=True)),
                ('bio', models.TextField(blank=True)),
                ('banner', models.ImageField(blank=True, upload_to=master_collection.models.Artist.art_dir)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('origin', models.CharField(blank=True, verbose_name='origin city')),
                ('profile', models.ImageField(blank=True, upload_to=master_collection.models.Artist.art_dir)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.TextField(blank=True)),
                ('album_cover', models.ImageField(blank=True, upload_to=master_collection.models.Album.art_dir)),
                ('spine_art', models.ImageField(blank=True, upload_to=master_collection.models.Album.art_dir)),
                ('contributing_artists', models.ManyToManyField(related_name='contributing_artists', to='master_collection.artist')),
                ('release_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_artist', to='master_collection.artist')),
            ],
            options={
                'unique_together': {('release_artist', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('order', models.IntegerField()),
                ('lyrics', models.TextField(blank=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_collection.album')),
            ],
            options={
                'unique_together': {('album', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(default='media', upload_to=master_collection.models.Recording.upload_dir, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])])),
                ('for_streaming', models.BooleanField(default=False)),
                ('recording', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_collection.track')),
            ],
        ),
    ]
