# Generated by Django 5.1.7 on 2025-03-13 19:25

import django.core.validators
import master_collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_collection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='master_recording',
            field=models.FileField(max_length=500, upload_to=master_collection.models.Track.master_upload_dir, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['flac'])]),
        ),
        migrations.AlterField(
            model_name='track',
            name='order',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='track',
            name='streamable_recording',
            field=models.FileField(blank=True, max_length=500, upload_to=master_collection.models.Track.streamable_upload_dir, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['aac'])]),
        ),
    ]
