# Generated by Django 5.1.7 on 2025-03-12 00:18

import django.core.validators
import django.db.models.deletion
import master_collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_collection', '0001_initialization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='recording',
        ),
        migrations.AddField(
            model_name='recording',
            name='track',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master_collection.track'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recording',
            name='file',
            field=models.FileField(upload_to=master_collection.models.Recording.upload_dir, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3'])]),
        ),
    ]
