# Generated by Django 5.1.7 on 2025-03-19 18:37

import django.core.files.storage
import django.core.validators
import master_collection.models.album
import master_collection.models.artist
import master_collection.models.track
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_collection', '0002_alter_track_master_recording_alter_track_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='banner_alt_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='profile_alt_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_cover',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(allow_overwrite=True), upload_to=master_collection.models.album.Album.art_dir, validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='album',
            name='spine_art',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(allow_overwrite=True), upload_to=master_collection.models.album.Album.art_dir, validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='artist',
            name='banner',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(allow_overwrite=True), upload_to=master_collection.models.artist.Artist.art_dir, validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(allow_overwrite=True), upload_to=master_collection.models.artist.Artist.art_dir, validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='track',
            name='master_recording',
            field=models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(allow_overwrite=True), upload_to=master_collection.models.track.Track.master_upload_dir, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['flac'])]),
        ),
        migrations.AlterField(
            model_name='track',
            name='streamable_recording',
            field=models.FileField(blank=True, max_length=500, storage=django.core.files.storage.FileSystemStorage(allow_overwrite=True), upload_to=master_collection.models.track.Track.streamable_upload_dir, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['aac'])]),
        ),
    ]
