# Generated by Django 5.1.7 on 2025-03-12 19:08

import django.core.validators
import django.db.models.deletion
import master_collection.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_collection', '0002_remove_recording_recording_recording_track_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['release_artist', '-release_date']},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='album',
            name='release_date',
            field=models.DateField(default='1900-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='album_cover',
            field=models.ImageField(blank=True, upload_to=master_collection.models.Album.art_dir, validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.AlterField(
            model_name='album',
            name='contributing_artists',
            field=models.ManyToManyField(blank=True, related_name='contributing_albums', to='master_collection.artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='master_collection.artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='spine_art',
            field=models.ImageField(blank=True, upload_to=master_collection.models.Album.art_dir, validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
