# Generated by Django 5.1.7 on 2025-03-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_collection', '0003_artist_banner_alt_text_artist_profile_alt_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_cover_alt_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='album',
            name='spine_art_alt_text',
            field=models.TextField(blank=True),
        ),
    ]
